name: CI
on:
  push:
    branches: [ app ]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'MaleneU'
        reponame: 'recipe-app'
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        VUE_APP_STRAPI: ${{ secrets.VUE_APP_STRAPI }}
